"use client";

import { useState, ReactNode } from "react";
import { useMutation, useQuery } from "convex/react";
import { api } from "../../convex/_generated/api";
import { Id } from "../../convex/_generated/dataModel";
import { useToast } from "./ui/Toast";

interface Reminder {
  _id: Id<"reminders">;
  type: "annual_review" | "life_event" | "document_update" | "beneficiary_review" | "custom" | "preparation_task";
  title: string;
  description?: string;
  lifeEvent?: string;
  dueDate: number;
  status: "pending" | "completed" | "snoozed" | "dismissed";
  priority: "low" | "medium" | "high" | "urgent";
  isRecurring: boolean;
  recurrencePattern?: string;
  parentReminderId?: Id<"reminders">;
  isAutoGenerated?: boolean;
  sourceType?: "gap_analysis" | "life_event" | "manual";
}

interface SubTaskCount {
  total: number;
  completed: number;
}

interface ReminderCardProps {
  reminder: Reminder;
  onComplete?: () => void;
  subTaskCount?: SubTaskCount;
}

// Icons for reminder types
const TYPE_ICONS: Record<string, ReactNode> = {
  annual_review: (
    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
    </svg>
  ),
  life_event: (
    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z" />
    </svg>
  ),
  document_update: (
    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
    </svg>
  ),
  beneficiary_review: (
    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0z" />
    </svg>
  ),
  custom: (
    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9" />
    </svg>
  ),
  preparation_task: (
    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-6 9l2 2 4-4" />
    </svg>
  ),
};

const PRIORITY_COLORS = {
  low: "bg-[var(--success-muted)] text-[var(--success)]",
  medium: "bg-[var(--info-muted)] text-[var(--info)]",
  high: "bg-[var(--warning-muted)] text-[var(--warning)]",
  urgent: "bg-[var(--error-muted)] text-[var(--error)]",
};

const TYPE_COLORS = {
  annual_review: "bg-[var(--quartz-dark)]",
  life_event: "bg-[var(--coral)]",
  document_update: "bg-[var(--info)]",
  beneficiary_review: "bg-[var(--success)]",
  custom: "bg-[var(--mushroom-grey)]",
  preparation_task: "bg-[var(--warning)]",
};

export function ReminderCard({ reminder, onComplete, subTaskCount }: ReminderCardProps) {
  const [showSnoozeMenu, setShowSnoozeMenu] = useState(false);
  const [isExpanded, setIsExpanded] = useState(false);
  const [showSubTasks, setShowSubTasks] = useState(false);

  const { addToast } = useToast();
  const completeReminder = useMutation(api.reminders.completeReminder);
  const snoozeReminder = useMutation(api.reminders.snoozeReminder);
  const dismissReminder = useMutation(api.reminders.dismissReminder);
  const completeParentIfAllDone = useMutation(api.reminders.completeParentIfAllChildrenDone);

  // Fetch sub-tasks if this reminder has them
  const subTasks = useQuery(
    api.reminders.getSubTasks,
    subTaskCount && subTaskCount.total > 0 ? { parentReminderId: reminder._id } : "skip"
  );

  const hasSubTasks = subTaskCount && subTaskCount.total > 0;

  const isOverdue = reminder.status === "pending" && reminder.dueDate < Date.now();
  const daysUntilDue = Math.ceil((reminder.dueDate - Date.now()) / (1000 * 60 * 60 * 24));

  const formatDueDate = (timestamp: number) => {
    const date = new Date(timestamp);
    return date.toLocaleDateString("en-US", {
      month: "short",
      day: "numeric",
      year: date.getFullYear() !== new Date().getFullYear() ? "numeric" : undefined,
    });
  };

  const handleComplete = async () => {
    await completeReminder({
      reminderId: reminder._id,
      createNextRecurrence: reminder.isRecurring,
    });

    // If this is a sub-task, check if parent should be completed
    if (reminder.parentReminderId) {
      await completeParentIfAllDone({ parentReminderId: reminder.parentReminderId });
    }

    addToast({
      type: "success",
      title: "Reminder completed",
      message: "Great job staying on top of your estate plan!",
    });

    onComplete?.();
  };

  const handleSubTaskComplete = async (subTaskId: Id<"reminders">) => {
    await completeReminder({
      reminderId: subTaskId,
      createNextRecurrence: false,
    });

    // Check if parent should be completed
    await completeParentIfAllDone({ parentReminderId: reminder._id });

    onComplete?.();
  };

  const handleSnooze = async (days: number) => {
    const snoozeUntil = Date.now() + (days * 24 * 60 * 60 * 1000);
    await snoozeReminder({
      reminderId: reminder._id,
      snoozeUntil,
    });
    setShowSnoozeMenu(false);

    addToast({
      type: "info",
      title: "Reminder snoozed",
      message: `We'll remind you again in ${days} day${days !== 1 ? "s" : ""}.`,
    });

    onComplete?.();
  };

  const handleDismiss = async () => {
    await dismissReminder({ reminderId: reminder._id });

    addToast({
      type: "info",
      title: "Reminder dismissed",
      message: "You can always create a new reminder if needed.",
    });

    onComplete?.();
  };

  if (reminder.status === "completed" || reminder.status === "dismissed") {
    return null;
  }

  return (
    <div className={`group relative bg-white dark:bg-[var(--charcoal)] rounded-xl border-2 transition-all duration-200 overflow-hidden ${
      isOverdue
        ? "border-[var(--error)] dark:border-[var(--error)]"
        : "border-[var(--border)] dark:border-[var(--border)] hover:border-[var(--stone-grey)] dark:hover:border-[var(--stone-grey)]"
    }`}>
      {/* Color accent bar */}
      <div className={`h-1 ${TYPE_COLORS[reminder.type]}`} />

      <div className="p-4">
        {/* Header */}
        <div className="flex items-start gap-3">
          {/* Icon */}
          <div className={`p-2 rounded-lg ${TYPE_COLORS[reminder.type]} text-white`}>
            {TYPE_ICONS[reminder.type]}
          </div>

          {/* Content */}
          <div className="flex-1 min-w-0">
            <div className="flex items-start justify-between gap-2">
              <h3 className="font-semibold text-gray-900 dark:text-white truncate">
                {reminder.title}
              </h3>

              {/* Priority badge */}
              <span className={`px-2 py-0.5 text-xs font-medium rounded-full ${PRIORITY_COLORS[reminder.priority]}`}>
                {reminder.priority}
              </span>
            </div>

            {/* Due date */}
            <div className={`flex items-center gap-2 mt-1 text-sm ${
              isOverdue ? "text-[var(--error)]" : "text-[var(--text-muted)]"
            }`}>
              <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" />
              </svg>
              <span>
                {isOverdue ? (
                  <>Overdue by {Math.abs(daysUntilDue)} day{Math.abs(daysUntilDue) !== 1 ? "s" : ""}</>
                ) : daysUntilDue === 0 ? (
                  "Due today"
                ) : daysUntilDue === 1 ? (
                  "Due tomorrow"
                ) : (
                  <>Due {formatDueDate(reminder.dueDate)} ({daysUntilDue} days)</>
                )}
              </span>

              {reminder.isRecurring && (
                <span className="flex items-center gap-1 text-[var(--coral)]">
                  <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" />
                  </svg>
                  {reminder.recurrencePattern}
                </span>
              )}
            </div>

            {/* Description (expandable) */}
            {reminder.description && (
              <button
                onClick={() => setIsExpanded(!isExpanded)}
                className="mt-2 text-sm text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-white flex items-center gap-1"
              >
                {isExpanded ? "Hide details" : "Show details"}
                <svg className={`w-3.5 h-3.5 transition-transform ${isExpanded ? "rotate-180" : ""}`} fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
                </svg>
              </button>
            )}

            {isExpanded && reminder.description && (
              <p className="mt-2 text-sm text-gray-600 dark:text-gray-400 bg-gray-50 dark:bg-gray-900/50 p-3 rounded-lg">
                {reminder.description}
              </p>
            )}

            {/* Sub-task progress indicator */}
            {hasSubTasks && (
              <button
                onClick={() => setShowSubTasks(!showSubTasks)}
                className="mt-3 w-full"
              >
                <div className="flex items-center justify-between mb-1">
                  <span className="text-xs font-medium text-gray-600 dark:text-gray-400">
                    Steps: {subTaskCount.completed}/{subTaskCount.total} complete
                  </span>
                  <svg
                    className={`w-4 h-4 text-gray-400 transition-transform ${showSubTasks ? "rotate-180" : ""}`}
                    fill="none"
                    stroke="currentColor"
                    viewBox="0 0 24 24"
                  >
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
                  </svg>
                </div>
                <div className="w-full bg-[var(--stone-grey)] dark:bg-[var(--charcoal)] rounded-full h-2">
                  <div
                    className="bg-[var(--success)] h-2 rounded-full transition-all duration-300"
                    style={{ width: `${(subTaskCount.completed / subTaskCount.total) * 100}%` }}
                  />
                </div>
              </button>
            )}

            {/* Auto-generated badge */}
            {reminder.isAutoGenerated && (
              <div className="mt-2 flex items-center gap-1 text-xs text-gray-400">
                <svg className="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" />
                </svg>
                Auto-generated from {reminder.sourceType === "gap_analysis" ? "analysis" : reminder.sourceType}
              </div>
            )}
          </div>
        </div>

        {/* Expandable Sub-tasks List */}
        {showSubTasks && subTasks && subTasks.length > 0 && (
          <div className="px-4 pb-4 space-y-2">
            <div className="border-t border-gray-100 dark:border-gray-700 pt-3">
              {subTasks.map((subTask, index) => (
                <div
                  key={subTask._id}
                  className={`flex items-center gap-3 py-2 ${
                    index !== subTasks.length - 1 ? "border-b border-gray-50 dark:border-gray-800" : ""
                  }`}
                >
                  <button
                    onClick={() => handleSubTaskComplete(subTask._id)}
                    disabled={subTask.status === "completed"}
                    className={`flex-shrink-0 w-5 h-5 rounded border-2 flex items-center justify-center transition-colors ${
                      subTask.status === "completed"
                        ? "bg-[var(--success)] border-[var(--success)] text-white"
                        : "border-[var(--border)] dark:border-[var(--stone-grey)] hover:border-[var(--success)] dark:hover:border-[var(--success)]"
                    }`}
                  >
                    {subTask.status === "completed" && (
                      <svg className="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} d="M5 13l4 4L19 7" />
                      </svg>
                    )}
                  </button>
                  <span
                    className={`text-sm ${
                      subTask.status === "completed"
                        ? "text-gray-400 line-through"
                        : "text-gray-700 dark:text-gray-300"
                    }`}
                  >
                    {subTask.title}
                  </span>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Actions */}
        <div className="flex items-center gap-2 mt-4 pt-3 border-t border-gray-100 dark:border-gray-700">
          {/* Complete button */}
          <button
            onClick={handleComplete}
            className="flex-1 flex items-center justify-center gap-2 px-3 py-2 bg-[var(--success)] text-white text-sm font-medium rounded-lg hover:opacity-90 transition-all"
          >
            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
            </svg>
            Complete
          </button>

          {/* Snooze button */}
          <div className="relative">
            <button
              onClick={() => setShowSnoozeMenu(!showSnoozeMenu)}
              className="flex items-center justify-center gap-1 px-3 py-2 bg-gray-100 dark:bg-gray-700 text-gray-700 dark:text-gray-300 text-sm font-medium rounded-lg hover:bg-gray-200 dark:hover:bg-gray-600 transition-all"
            >
              <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" />
              </svg>
              Snooze
            </button>

            {/* Snooze dropdown */}
            {showSnoozeMenu && (
              <div className="absolute right-0 mt-1 w-40 bg-white dark:bg-gray-800 rounded-lg shadow-lg border border-gray-200 dark:border-gray-700 z-10">
                <button
                  onClick={() => handleSnooze(1)}
                  className="w-full px-3 py-2 text-sm text-left text-gray-700 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-700 first:rounded-t-lg"
                >
                  1 day
                </button>
                <button
                  onClick={() => handleSnooze(3)}
                  className="w-full px-3 py-2 text-sm text-left text-gray-700 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-700"
                >
                  3 days
                </button>
                <button
                  onClick={() => handleSnooze(7)}
                  className="w-full px-3 py-2 text-sm text-left text-gray-700 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-700"
                >
                  1 week
                </button>
                <button
                  onClick={() => handleSnooze(30)}
                  className="w-full px-3 py-2 text-sm text-left text-gray-700 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-700 last:rounded-b-lg"
                >
                  1 month
                </button>
              </div>
            )}
          </div>

          {/* Dismiss button */}
          <button
            onClick={handleDismiss}
            className="flex items-center justify-center p-2 text-gray-400 hover:text-gray-600 dark:hover:text-gray-300 transition-colors"
            title="Dismiss"
          >
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>
      </div>
    </div>
  );
}

export default ReminderCard;
